### ISSUE TITLE
Browserify the code?

### ISSUE THREAD

**Issue by orels1** [pingyhq/pingy-cli#13]
First of all - thanks for a great tool, which will come in handy many times for smaller projects (like landing pages and so on.

But I really wish that you would browserify the code, so I could `import React from 'react'` for example.

If I'm doing something wrong - it'll be cool to know

**Comment by davej** [comment]
I want to keep it super simple for the moment. As bugs are ironed out and 1.0 is released, I'll start exploring if there's a simple way to support modules. Thanks for your feedback! :)

**Comment by mtimofiiv** [comment]
+1 on this feature request - would be fantastic.

Currently, I really love this project, but I can't use it anywhere except the simplest landing pages.

**Comment by davej** [comment]
Noted.

I've given this a post-v1.0 milestone tag. I'll reopen and re-investigate once 1.0 is released. For now, I'm keeping any issue that is post 1.0 closed.

**Comment by Daidalos117** [comment]
And what is the easiest ways to make it work? Thank you.

**Comment by mtimofiiv** [comment]
@Daidalos117 I suppose integrating `browserify` into the module would be easiest.

**Comment by lunelson** [comment]
Another option for those who are just using Pingy as a quick prototyping tool, would be to offer a  Javascript option that leverages native ES Modules support in bleeding-edge browsers, by using `type="module"` on the script tag. It requires enabling a special flag on the browser; but otherwise would 'just work'. You might call it `Javascript ESM` for example, to differentiate from the straight `Javascript` option. Implicitly, a lot of ESx features come with it too, without the need for Babel. Or, there may be a configuration of Babel too, which will transpile ES7+ plus things without trying to convert `import`s to `require`s?

```html
<script type="module" src="module.js"></script>
```
REF: https://medium.com/dev-channel/es6-modules-in-chrome-canary-m60-ba588dfb8ab7

**Comment by lunelson** [comment]
It seems you can add a [`modules: false`](https://github.com/babel/babel/tree/master/experimental/babel-preset-env#modules) option to the `.babelrc` file options for `babel-preset-env`, to disable changing of the module format

**Comment by davej** [comment]
Thanks @lunelson, that's very helpful.

**Comment by lunelson** [comment]
Glad to help. The only snag seems to be that changes to `.js` files other than the main one don't trigger a livereload event. If you choose to implement these suggestions that would need some kind of patch too.

**Comment by davej** [comment]
> The only snag seems to be that changes to .js files other than the main one don't trigger a livereload event.

Ah, I'll consider that a bug and create an issue for it. Thanks!

**Comment by davej** [comment]
@lunelson: As of [v0.9.5](https://github.com/pingyhq/pingy-cli/releases/tag/%40pingy%2Fcli%400.9.5), Live reload should now work with `type="module"` scripts.
