### ISSUE TITLE
Moving between computers

### ISSUE THREAD

**Issue by mikestreety** [pingyhq/pingy-cli#45]
Hello!

I love pingy and have been using it for static sites. However, I just cloned down a project with a `.pingy.json` file, run `pingy dev` and it appeared to work, except none of the JS or CSS was being loaded in.

It turns out I was missing some compilers, but nothing told me. I had to redo `pingy init` making sure I selected the right options again, deny it the chance to make a scaffold and _then_ it detected it needed to install sass.

Anyway I can get it to do this check without running an `init`?

**Comment by davej** [comment]
Just run `npm install`, you don't need to run `npm init`.

 If you copy the site with `node_modules` included then you may not even need to run `npm install`, the caveat is if you're using Sass (because it's a C library that needs to built natively). If you're using Sass then you can just run `npm rebuild`.
