### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by indus** [pingyhq/pingy-cli#7]
Would like to see Typescript support.

**Comment by davej** [comment]
I've just added beta support in `0.6.4` on Pingy CLI. The install procedure is a bit weird for the moment and it's untested so that's why I'm keeping it in beta and not adding it to `pingy init` yet.

To get it working:

* You have to install `^1.4` specifically because of this issue: https://github.com/theblacksmith/typescript-compiler/issues/15
```
npm install --save-dev typescript-compiler@^1.4
```

* Save your typescript files with the `.ts` extension and reference them with `.js` (just like every other compiled file).

**Comment by davej** [comment]
@indus If you get a chance to test out this functionality then it would be really helpful. 👍

**Comment by indus** [comment]
@davej couln´t get it to work. I´ve installed it in a newly pingy-created project., But no typescript compilation after renaming main.js -> main.ts.

**Comment by davej** [comment]
When you run `pingy dev` what version does it say and is it global or local?

**Comment by indus** [comment]
0.6.3 (global). Has to be local? Would be another exaple for the list in https://github.com/pingyhq/pingy-cli/issues/8#issuecomment-300386183 ;-)

**Comment by indus** [comment]
oops v0.6.3 !=v0.6.4. Sorry my fault

**Comment by indus** [comment]
0.6.4 (global). Works! Nice, thanks!

**Comment by davej** [comment]
Added typescript to `pingy init`, as of 0.6.13.

<img width="311" alt="screen shot 2017-06-27 at 19 47 52" src="https://user-images.githubusercontent.com/26971/27604616-b8364638-5b71-11e7-8e87-2c417585ecd0.png">
