### ISSUE TITLE
[scaffold] needs name and description fields?

### ISSUE THREAD

**Issue by filtercake** [pingyhq/pingy-cli#71]
> You do not need to include a name key as this is calculated based on the folder name that the site is being scaffolded into.

- https://github.com/pingyhq/pingy-cli/wiki/Creating-a-custom-scaffold#pingyjson

```
$ pingy scaffold ../pingy-scaffold-pug-sass/

0.10.1 (global)
  ____  _
 |  _ \(_)_ __   __ _ _   _
 | |_) | | '_ \ / _` | | | |
 |  __/| | | | | (_| | |_| |
 |_|   |_|_| |_|\__, |\__, |
                |___/ |___/

Error: pingy-scaffold.json should contain a name and a description
```

it works when name and description are added.

to edit the wiki i need to clone it? how do send a pr though?

**Comment by davej** [comment]
> You do not need to include a name key as this is calculated based on the folder name that the site is being scaffolded into.

Ah, this is confusing for sure. This is referring to a the `pingyJson` key. So..

```
{
  "name": "required",
  "description": "required",
  "pingyJson": {
    "name": "NOT required",
    "description": "NOT required",
  }
}
```

This definitely needs to be documented better because I don't even mention the root name and description in the wiki article. If you want to edit then that will be awesome. If not then I'll get around to it tomorrow.

> to edit the wiki i need to clone it? how do send a pr though?

I don't think you can PR a wiki but if you link me to your wiki repo then I can do a diff I guess.

**Comment by davej** [comment]
Wiki updated. Thanks!
