### ISSUE TITLE
Autoprefix styles

### ISSUE THREAD

**Issue by jewbetcha** [pingyhq/pingy-cli#9]
Great job with Pingy CLI! Super cool.

The only thing I feel like I'm missing is autoprefixing of styles, any way to add that myself? Or plans to add it?

**Comment by randallmlough** [comment]
+1 for this!

**Comment by davej** [comment]
This is on the todo list. I don't think I want to enable it by default, so I think I'll make it an option in the `.pingy.json` file.

{Gasp}... I guess that counts as configuration! 😃

**Comment by themezzilla** [comment]
Woot :raised_hands: sounds good!

**Comment by randallmlough** [comment]
I think that's an acceptable config! 

Btw - I know you're going for a _no config required_ with this, but for some advanced options - this for example - I think having some config options is perfectly acceptable!

**Comment by sjclark** [comment]
This tool is fantastic but the lack of auto-prefixer stops me using it for now - don't think I've ever had a gulp (or brunch) config without auto-prefixing. Is there any reason why prefixing couldn't just be built-in? Rather than an "advanced option"? (ie. does it break / cause problems with any common workflows?)

**Comment by davej** [comment]
@sjclark My issue is that vendor-prefixes are not being used by browser vendors anymore, so I'm wary of adding bloat that won't be so relevant in a couple of years. Having said that, I'll add it as a configuration option. Might be ready by tomorrow.

**Comment by sjclark** [comment]
> won't be so relevant in a **couple of years**

Guess thats the key, still very relevant for now - i know you're anti-config but what if you had a vendor-prefix config line that just took the arguments ie: `'last 2 versions','iOS >= 8','Safari >= 8'` - don't need any prefixing then don't put anything?

Even with that config line above (which I consider liberal) my clients complain that "Oh, it doesn't seem to work on my daughters iPad" - although everyone signs a contract that stipulates it will support the latest version of IE, Edge, Chrome (&mobile), Firefox, and nothing else. Clients be clients.

**Comment by davej** [comment]
>  i know you're anti-config but what if you had a vendor-prefix config line that just took the arguments ie: 'last 2 versions','iOS >= 8','Safari >= 8' - don't need any prefixing then don't put anything?

That's exactly what I'm doing, hopefully, it will be ready for tomorrow.

**Comment by ronilaukkarinen** [comment]
Thanks for this project. Been using gulp from the very start and autoprefix is the essential feature. Will wait for pingy to mature, then going to give it another chance.

**Comment by davej** [comment]
Hey everyone, this is available in 0.7.0 beta. 🎉

Details of the release and how to install it are here: https://github.com/pingyhq/pingy-cli/releases/tag/%40pingy%2Fcli%400.7.0

I would very much appreciate your help in testing it out. 👍

**Comment by themezzilla** [comment]
This is working well for me!

**Comment by Munter** [comment]
You could use the browsers field in package.json which it seems the community is converging on. If it's there, autoprefix. If it's not, don't. I think that would be a fair convention

**Comment by davej** [comment]
@Munter Good idea, I didn't know about that. I'll add support 👍.

**Comment by Munter** [comment]
@davej Looks like you won't even have to: https://github.com/ai/browserslist/blob/master/index.js#L158-L288

Seems you can use this to get the config from the already supported configuration conventions. Then decide what to do based on the return value I think.

**Comment by davej** [comment]
This is out of beta for `v0.8`+.

I'm not adding `browsers` in `package.json` support yet because I need to think about it more and possibly also consider whether it should also be honoured by Babel and passed along to `babel-preset-env`.

Usage
------

To enable autoprefix then just add the following entry to your `.pingy.json`:

```
{
  //...
  "autoprefix": true,
  //...
}
```

This will default to autoprefixing for the last 2 browser versions if set to `true`. But you can also set it to a `string` or an `array` of `strings` (e.g.. `["> 5%", "last 1 version"]`). [More info on available queries here](https://github.com/ai/browserslist#queries).

**Comment by davej** [comment]
Closing as this feature is considered stable as of v0.10. Support for the `browsers` property in `package.json` will be tracked in #70.
